# docker-compose.dev.yml
# run locally with `docker compose -f docker-compose.dev.yml up`
# this is for development only, does not include the tor service.
services:
  caddy:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: lighthouse-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-lighthouse} # default to "lighthouse" if not set in .env
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-lighthouse_secret} # default to "lighthouse_secret" if not set in .env
    ports:
      - "9000:9000"   # for backend
      - "9001:9001"   # console web panel
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio-init:
    image: minio/mc
    container_name: lighthouse-minio-init
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-lighthouse} # default to "lighthouse" if not set in .env
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-lighthouse_secret} # default to "lighthouse_secret" if not set in .env
    entrypoint: >
      /bin/sh -c "
        mc alias set local http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD &&
        mc mb --ignore-existing local/lighthouse &&
        echo 'Bucket lighthouse created.'
      "
    restart: on-failure

volumes:
  caddy_data:
  caddy_config:
  minio_data: