/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesteRouteImport } from './routes/teste'
import { Route as FetchRouteImport } from './routes/fetch'
import { Route as IndexRouteImport } from './routes/index'

const TesteRoute = TesteRouteImport.update({
  id: '/teste',
  path: '/teste',
  getParentRoute: () => rootRouteImport,
} as any)
const FetchRoute = FetchRouteImport.update({
  id: '/fetch',
  path: '/fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fetch': typeof FetchRoute
  '/teste': typeof TesteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fetch': typeof FetchRoute
  '/teste': typeof TesteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fetch': typeof FetchRoute
  '/teste': typeof TesteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fetch' | '/teste'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fetch' | '/teste'
  id: '__root__' | '/' | '/fetch' | '/teste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FetchRoute: typeof FetchRoute
  TesteRoute: typeof TesteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teste': {
      id: '/teste'
      path: '/teste'
      fullPath: '/teste'
      preLoaderRoute: typeof TesteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fetch': {
      id: '/fetch'
      path: '/fetch'
      fullPath: '/fetch'
      preLoaderRoute: typeof FetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FetchRoute: FetchRoute,
  TesteRoute: TesteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
